role,groupName,hostName,serviceName,dbPath

catalog,SYSCatalogGroup,[host1],11800,/data/sequoiadb/database/catalog/11800
catalog,SYSCatalogGroup,[host2],11800,/data/sequoiadb/database/catalog/11800
catalog,SYSCatalogGroup,[host3],11800,/data/sequoiadb/database/catalog/11800

coord,SYSCoord,[host1],11810,/data/sequoiadb/database/coord/11810
coord,SYSCoord,[host2],11810,/data/sequoiadb/database/coord/11810
coord,SYSCoord,[host3],11810,/data/sequoiadb/database/coord/11810

data,group1,[host1],11820,/data/sequoiadb/database/data/11820
data,group1,[host2],11820,/data/sequoiadb/database/data/11830
data,group1,[host3],11820,/data/sequoiadb/database/data/11840

